apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- ../fv3net/workflows/argo
kind: Kustomization
images:
- name: us.gcr.io/vcm-ml/fv3net
  newTag: ae9b07271ae0133cc7099aacaf5081db77455739
- name: us.gcr.io/vcm-ml/fv3fit
  newTag: ae9b07271ae0133cc7099aacaf5081db77455739
- name: us.gcr.io/vcm-ml/post_process_run
  newTag: ae9b07271ae0133cc7099aacaf5081db77455739
- name: us.gcr.io/vcm-ml/prognostic_run
  newTag: ae9b07271ae0133cc7099aacaf5081db77455739