base_version: v0.7
prephysics:
  - dataset_key: "gs://vcm-ml-intermediate/2021-03-fine-res-surface-radiative-fluxes/10day-PIRE-ccnorm-v2-coarsened-surface-radiative-fluxes-precip.zarr"
    variables:
      override_for_time_adjusted_total_sky_downward_shortwave_flux_at_surface: override_for_time_adjusted_total_sky_downward_shortwave_flux_at_surface
      override_for_time_adjusted_total_sky_downward_longwave_flux_at_surface: override_for_time_adjusted_total_sky_downward_longwave_flux_at_surface
      override_for_time_adjusted_total_sky_net_shortwave_flux_at_surface: override_for_time_adjusted_total_sky_net_shortwave_flux_at_surface
      total_precipitation: total_precipitation
initial_conditions:
  base_url: gs://vcm-ml-raw-flexible-retention/2023-06-29-PIRE-and-FV3GFS-like-C3072-ccnorm-true-simulation/C3072-to-C48-restarts-re-upload
  timestep: "20200731.060000"
nudging:
  restarts_path: gs://vcm-ml-raw-flexible-retention/2023-06-29-PIRE-and-FV3GFS-like-C3072-ccnorm-true-simulation/C3072-to-C48-restarts-re-upload
  timescale_hours:
    air_temperature: 3
    specific_humidity: 3
    x_wind: 3
    y_wind: 3
    pressure_thickness_of_atmospheric_layer: 3
radiation_scheme:
  kind: "python"
  input_generator:
    dataset_key: gs://vcm-ml-experiments/cloud-ml/2023-07-04/cloud-ml-training-data.zarr
    variables:
      cloud_water_mixing_ratio: cloud_water_mixing_ratio
      cloud_ice_mixing_ratio: cloud_ice_mixing_ratio
      cloud_amount: cloud_amount
    reference_initial_time: "20200731.060000"
    reference_frequency_seconds: 900
namelist:
  atmos_model_nml:
    fhmax: 1024  # max hours of simulation (over all segments) for which fortran physics diags are saved
  coupler_nml:
    days: 0
    hours: 6
    minutes: 0
    months: 0
    seconds: 0
  gfdl_cloud_microphysics_nml:
    mp_time: 150.0
  gfs_physics_nml:
    fhzero: 0.25
    fhlwr: 900.0
    fhswr: 900.0
    iovr_sw: 1
    iovr_lw: 1
    ccnorm: True
    override_surface_radiative_fluxes: true
    hybedmf: true
    satmedmf: false
    xkzm_h: 2.0
  fv_core_nml:
    layout:
      - 2
      - 2
  namsfc:
    ftsfs: 90 # SSTs should be overwritten by nudging, anyway
    fsnol: 0 # set snow covered area to climatology
    fsnos: 0 # set snow covered area to climatology
    faisl: 99999 # Persist land / sea / sea-ice mask from the initial conditions instead of using climatology forcing files
    faiss: 99999 # Persist land / sea / sea-ice mask from the initial conditions instead of using climatology forcing files
    fsicl: 99999 # Persist the sea ice fraction from the initial conditiond instead of using climatology forcing files
    fsics: 99999 # Persist the sea ice fraction from the initial conditiond instead of using climatology forcing files
diagnostics:
- name: radiative_fluxes.zarr
  chunks:
    time: 4
  times:
    frequency: 900
    kind: interval
  variables:
  - clear_sky_downward_longwave_flux_at_surface_python
  - clear_sky_downward_shortwave_flux_at_surface_python
  - clear_sky_upward_longwave_flux_at_surface_python
  - clear_sky_upward_shortwave_flux_at_surface_python
  - clear_sky_upward_longwave_flux_at_top_of_atmosphere_python
  - clear_sky_upward_shortwave_flux_at_top_of_atmosphere_python
  - total_sky_downward_longwave_flux_at_surface_python
  - total_sky_downward_shortwave_flux_at_surface_python
  - total_sky_upward_longwave_flux_at_surface_python
  - total_sky_upward_shortwave_flux_at_surface_python
  - total_sky_downward_shortwave_flux_at_top_of_atmosphere_python
  - total_sky_upward_longwave_flux_at_top_of_atmosphere_python
  - total_sky_upward_shortwave_flux_at_top_of_atmosphere_python
  - total_sky_longwave_heating_rate_python
  - clear_sky_longwave_heating_rate_python
  - total_sky_shortwave_heating_rate_python
  - clear_sky_shortwave_heating_rate_python
- name: diags.zarr
  chunks:
    time: 4
  times:
    frequency: 900
    kind: interval
  variables:
  - net_moistening_due_to_nudging
  - column_heating_due_to_nudging
  - net_mass_tendency_due_to_nudging
  - total_precipitation_rate
  - water_vapor_path
  - physics_precip
fortran_diagnostics:
- name: sfc_dt_atmos.zarr
  chunks:
    time: 4
  times:
    frequency: 900
    kind: interval
  variables:
  - {module_name: dynamics, field_name: grid_lont, output_name: lon}
  - {module_name: dynamics, field_name: grid_latt, output_name: lat}
  - {module_name: dynamics, field_name: grid_lon, output_name: lonb}
  - {module_name: dynamics, field_name: grid_lat, output_name: latb}
  - {module_name: dynamics, field_name: area, output_name: area}
  - {module_name: gfs_phys, field_name: dusfci, output_name: uflx}
  - {module_name: gfs_phys, field_name: dvsfci, output_name: vflx}
  - {module_name: gfs_phys, field_name: cnvprcpb_ave, output_name: CPRATsfc}
  - {module_name: gfs_phys, field_name: totprcpb_ave, output_name: PRATEsfc}
  - {module_name: gfs_phys, field_name: toticeb_ave, output_name: ICEsfc}
  - {module_name: gfs_phys, field_name: totsnwb_ave, output_name: SNOWsfc}
  - {module_name: gfs_phys, field_name: totgrpb_ave, output_name: GRAUPELsfc}
  - {module_name: gfs_phys, field_name: DSWRF, output_name: DSWRFsfc}
  - {module_name: gfs_phys, field_name: DSWRF_from_rrtmg, output_name: DSWRFsfc_from_RRTMG}
  - {module_name: gfs_phys, field_name: DSWRFI, output_name: DSWRFIsfc}
  - {module_name: gfs_phys, field_name: csdsf_ave, output_name: DCSWRFsfc}
  - {module_name: gfs_phys, field_name: USWRF, output_name: USWRFsfc}
  - {module_name: gfs_phys, field_name: USWRF_from_rrtmg, output_name: USWRFsfc_from_RRTMG}
  - {module_name: gfs_phys, field_name: USWRFI, output_name: USWRFIsfc}
  - {module_name: gfs_phys, field_name: csusf_ave, output_name: UCSWRFsfc}
  - {module_name: gfs_phys, field_name: DSWRFtoa, output_name: DSWRFtoa}
  - {module_name: gfs_phys, field_name: sw_dnfxc, output_name: DSWRFItoa}
  - {module_name: gfs_phys, field_name: USWRFtoa, output_name: USWRFtoa}
  - {module_name: gfs_phys, field_name: sw_upfxc, output_name: USWRFItoa}
  - {module_name: gfs_phys, field_name: csusf_avetoa, output_name: UCSWRFtoa}
  - {module_name: gfs_phys, field_name: ULWRFtoa, output_name: ULWRFtoa}
  - {module_name: gfs_phys, field_name: lw_upfxc, output_name: ULWRFItoa}
  - {module_name: gfs_phys, field_name: csulf_avetoa, output_name: UCLWRFtoa}
  - {module_name: gfs_phys, field_name: ULWRF, output_name: ULWRFsfc}
  - {module_name: gfs_phys, field_name: ULWRFI, output_name: ULWRFIsfc}
  - {module_name: gfs_phys, field_name: csulf_ave, output_name: UCLWRFsfc}
  - {module_name: gfs_phys, field_name: DLWRF, output_name: DLWRFsfc}
  - {module_name: gfs_phys, field_name: DLWRF_from_rrtmg, output_name: DLWRFsfc_from_RRTMG}
  - {module_name: gfs_phys, field_name: DLWRFI, output_name: DLWRFIsfc}
  - {module_name: gfs_phys, field_name: csdlf_ave, output_name: DCLWRFsfc}
  - {module_name: gfs_phys, field_name: lhtfl_ave, output_name: LHTFLsfc}
  - {module_name: gfs_phys, field_name: shtfl_ave, output_name: SHTFLsfc}
  - {module_name: gfs_phys, field_name: hpbl, output_name: HPBLsfc}
  - {module_name: gfs_sfc, field_name: fice, output_name: ICECsfc}
  - {module_name: gfs_sfc, field_name: SLMSKsfc, output_name: SLMSKsfc}
  - {module_name: gfs_sfc, field_name: q2m, output_name: SPFH2m}
  - {module_name: gfs_sfc, field_name: t2m, output_name: TMP2m}
  - {module_name: gfs_sfc, field_name: tsfc, output_name: TMPsfc}
  - {module_name: gfs_phys, field_name: dpt2m, output_name: DPT2m}
  - {module_name: gfs_phys, field_name: u10m, output_name: UGRD10m}
  - {module_name: gfs_phys, field_name: v10m, output_name: VGRD10m}
  - {module_name: gfs_phys, field_name: tmpmax2m, output_name: TMAX2m}
  - {module_name: gfs_phys, field_name: wind10mmax, output_name: MAXWIND10m}
  - {module_name: gfs_phys, field_name: soilm, output_name: SOILM}
  - {module_name: gfs_sfc, field_name: SOILT1, output_name: SOILT1}
  - {module_name: gfs_sfc, field_name: SOILT2, output_name: SOILT2}
  - {module_name: gfs_sfc, field_name: SOILT3, output_name: SOILT3}
  - {module_name: gfs_sfc, field_name: SOILT4, output_name: SOILT4}
- name: atmos_dt_atmos.zarr
  chunks:
    time: 4
  times:
    frequency: 900
    kind: interval
  variables:
  - {module_name: dynamics, field_name: grid_lont, output_name: lon}
  - {module_name: dynamics, field_name: grid_latt, output_name: lat}
  - {module_name: dynamics, field_name: grid_lon, output_name: lonb}
  - {module_name: dynamics, field_name: grid_lat, output_name: latb}
  - {module_name: dynamics, field_name: area, output_name: area}
  - {module_name: dynamics, field_name: us, output_name: UGRDlowest}
  - {module_name: dynamics, field_name: u850, output_name: UGRD850}
  - {module_name: dynamics, field_name: u500, output_name: UGRD500}
  - {module_name: dynamics, field_name: u200, output_name: UGRD200}
  - {module_name: dynamics, field_name: u50, output_name: UGRD50}
  - {module_name: dynamics, field_name: vs, output_name: VGRDlowest}
  - {module_name: dynamics, field_name: v850, output_name: VGRD850}
  - {module_name: dynamics, field_name: v500, output_name: VGRD500}
  - {module_name: dynamics, field_name: v200, output_name: VGRD200}
  - {module_name: dynamics, field_name: v50, output_name: VGRD50}
  - {module_name: dynamics, field_name: tm, output_name: TMP500_300}
  - {module_name: dynamics, field_name: tb, output_name: TMPlowest}
  - {module_name: dynamics, field_name: t850, output_name: TMP850}
  - {module_name: dynamics, field_name: t500, output_name: TMP500}
  - {module_name: dynamics, field_name: t200, output_name: TMP200}
  - {module_name: dynamics, field_name: w850, output_name: w850}
  - {module_name: dynamics, field_name: w500, output_name: w500}
  - {module_name: dynamics, field_name: w200, output_name: w200}
  - {module_name: dynamics, field_name: w50, output_name: w50}
  - {module_name: dynamics, field_name: vort850, output_name: VORT850}
  - {module_name: dynamics, field_name: vort500, output_name: VORT500}
  - {module_name: dynamics, field_name: vort200, output_name: VORT200}
  - {module_name: dynamics, field_name: z850, output_name: h850}
  - {module_name: dynamics, field_name: z500, output_name: h500}
  - {module_name: dynamics, field_name: z200, output_name: h200}
  - {module_name: dynamics, field_name: rh1000, output_name: RH1000}
  - {module_name: dynamics, field_name: rh925, output_name: RH925}
  - {module_name: dynamics, field_name: rh850, output_name: RH850}
  - {module_name: dynamics, field_name: rh700, output_name: RH700}
  - {module_name: dynamics, field_name: rh500, output_name: RH500}
  - {module_name: dynamics, field_name: rh200, output_name: RH200}
  - {module_name: dynamics, field_name: q1000, output_name: q1000}
  - {module_name: dynamics, field_name: q925, output_name: q925}
  - {module_name: dynamics, field_name: q850, output_name: q850}
  - {module_name: dynamics, field_name: q700, output_name: q700}
  - {module_name: dynamics, field_name: q500, output_name: q500}
  - {module_name: dynamics, field_name: q200, output_name: q200}
  - {module_name: dynamics, field_name: slp, output_name: PRMSL}
  - {module_name: dynamics, field_name: ps, output_name: PRESsfc}
  - {module_name: dynamics, field_name: tq, output_name: PWAT}
  - {module_name: dynamics, field_name: lw, output_name: VIL}
  - {module_name: dynamics, field_name: iw, output_name: iw}
  - {module_name: dynamics, field_name: ke, output_name: kinetic_energy}
  - {module_name: dynamics, field_name: te, output_name: total_energy}
  - {module_name: dynamics, field_name: column_fv_sat_adj_heating, output_name: column_fv_sat_adj_heating}
  - {module_name: dynamics, field_name: column_fv_sat_adj_moistening, output_name: column_fv_sat_adj_moistening}
- name: atmos_dt_atmos_3d.zarr
  chunks:
    time: 1
  times:
    frequency: 3600
    kind: interval
  variables:
  - {module_name: dynamics, field_name: grid_lont, output_name: lon}
  - {module_name: dynamics, field_name: grid_latt, output_name: lat}
  - {module_name: dynamics, field_name: grid_lon, output_name: lonb}
  - {module_name: dynamics, field_name: grid_lat, output_name: latb}
  - {module_name: dynamics, field_name: fv_sat_adj_qv_dt, output_name: fv_sat_adj_qv_dt}
  - {module_name: dynamics, field_name: fv_sat_adj_t_dt, output_name: fv_sat_adj_t_dt}