apiVersion: v1
kind: Pod
metadata:
  name: fine-restarts-to-zarr
spec:
  volumes:
    - name: gcp-credentials-user-gcp-sa
      secret:
        secretName: gcp-key
  containers:
    - name: main
      image: us.gcr.io/vcm-ml/fv3net:ae9b07271ae0133cc7099aacaf5081db77455739
      command: ["bash", "-x", "-c"]
      workingDir: /home/jovyan/fv3net/workflows/dataflow
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/gcp-credentials/key.json
        - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
          value: /secret/gcp-credentials/key.json
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumeMounts:
        - mountPath: /secret/gcp-credentials
          name: gcp-credentials-user-gcp-sa
      args:
        - |
          ./dataflow.sh submit -m fv3net.pipelines.restarts_to_zarr \
            gs://vcm-ml-raw-flexible-retention/2023-06-29-PIRE-and-FV3GFS-like-C3072-ccnorm-true-simulation/C3072-to-C48-restarts-re-upload \
            gs://vcm-ml-intermediate/2023-06-30-PIRE-like-C3072-ccnorm-true-simulation-restarts.zarr \
            --no-coarse-suffix \
            --job_name $POD_NAME-$(openssl rand -hex 6) \
            --project vcm-ml \
            --region us-central1 \
            --runner DataFlow \
            --temp_location gs://vcm-ml-scratch/tmp_dataflow \
            --num_workers 64 \
            --autoscaling_algorithm=NONE
      resources:
        limits:
          memory: 2Gi
          cpu: "1000m"
        requests:
          memory: 1Gi
          cpu: "1000m"
  tolerations:
    - effect: NoSchedule
      key: dedicated
      value: med-sim-pool
  restartPolicy: Never